apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schema-registry
  # namespace: kafka
spec:
  replicas: 1
  config:
    kafkastore.bootstrap.servers: "PLAINTEXT://kafka:9092"
    kafkastore.topic: "_schemas"
  podTemplate:
    tolerations:
      - key: "kafka-only"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
