apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-spark
  labels:
    app: se-spark
spec:
  selector:
    matchLabels:
      app: se-spark
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: se-spark
    spec:
      containers:
      - image: gcr.io/cmu14848-435323/oooscarrrr/se-spark
        env:
          - name: JAVA_HOME
            value: /usr/lib/jvm/java-11-openjdk-amd64
        imagePullPolicy: Always
        name: se-spark
        ports:
          - containerPort: 5001
